/**
 * Wallet helper for the five-agent demo.
 *
 * Safe default:
 *   npm run wallets
 *     - Reads AGENT_MNEMONIC or per-agent private keys from env.
 *     - Prints public addresses only.
 *
 * Generate a fresh mnemonic:
 *   GENERATE_MNEMONIC=1 npm run wallets
 *     - Prints an .env snippet with a new mnemonic and the five derived
 *       public addresses. Do not commit the mnemonic.
 */

import { generateMnemonic, mnemonicToAccount } from "viem/accounts";
import { english } from "viem/accounts";
import { loadAgentWallets, loadProjectEnv } from "@clawdao/core/node";
import type { AgentSlug } from "@clawdao/core";
import { chmodSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SLUGS: AgentSlug[] = ["researcher", "risk", "executor", "auditor", "validator"];

function path(index: number): `m/44'/60'/0'/0/${number}` {
  return `m/44'/60'/0'/0/${index}` as const;
}

function printGenerated(): void {
  const mnemonic = generateMnemonic(english);
  const envPath = resolve(process.cwd(), "../.env.generated");
  writeFileSync(
    envPath,
    [
      "# Generated by GENERATE_MNEMONIC=1 npm run wallets",
      "# Move this into .env when you are ready. Never commit it.",
      `AGENT_MNEMONIC="${mnemonic}"`,
      "MANTLE_SEPOLIA_RPC_URL=https://rpc.sepolia.mantle.xyz",
      "EXECUTOR=auto",
      "BYREAL_MODE=mock",
      "AGENT_URI_MODE=data",
      ""
    ].join("\n"),
    { encoding: "utf8" }
  );
  chmodSync(envPath, 0o600);

  // eslint-disable-next-line no-console
  console.log(`Generated fresh AGENT_MNEMONIC into ${envPath}`);
  // eslint-disable-next-line no-console
  console.log("The mnemonic is not printed by default. Keep .env.generated private.\n");
  if (process.env.PRINT_MNEMONIC === "1") {
    // eslint-disable-next-line no-console
    console.log("AGENT_MNEMONIC=\"" + mnemonic + "\"\n");
  }
  // eslint-disable-next-line no-console
  console.log("Derived agent addresses:");
  SLUGS.forEach((slug, index) => {
    const derivationPath = path(index);
    const account = mnemonicToAccount(mnemonic, { path: derivationPath });
    // eslint-disable-next-line no-console
    console.log(`  ${slug.padEnd(10)} ${account.address}  ${derivationPath}`);
  });
  // eslint-disable-next-line no-console
  console.log("\nFund all five addresses with Mantle Sepolia testnet MNT before broadcasting.");
}

function printExisting(): void {
  const wallets = loadAgentWallets({ allowEphemeral: false });
  // eslint-disable-next-line no-console
  console.log("Resolved five agent wallets from environment:\n");
  for (const wallet of wallets) {
    // eslint-disable-next-line no-console
    console.log(
      `${wallet.slug.padEnd(10)} ${wallet.address}  source=${wallet.source}${
        wallet.derivationPath ? ` path=${wallet.derivationPath}` : ""
      }`
    );
  }
}

function main(): void {
  loadProjectEnv({ includeGenerated: true });
  if (process.env.GENERATE_MNEMONIC === "1") {
    printGenerated();
    return;
  }
  printExisting();
}

try {
  main();
} catch (error) {
  // eslint-disable-next-line no-console
  console.error((error as Error).message);
  // eslint-disable-next-line no-console
  console.error("\nSet AGENT_MNEMONIC, per-agent private keys, or run GENERATE_MNEMONIC=1 npm run wallets.");
  process.exit(1);
}
